Repository lambdaclass/cairo-vm, pull requests merged in 2023-06, with the labels that each got.

#1196 fix README.md
  README.md
Labels: coverage

#1219 Add CI flags to `run_benchmarks` script
  bench/run_benchmarks.sh
Labels: pipelines

#1180 Add factorial tests
  cairo_programs/cairo-1-contracts/factorial.cairo
  vm/src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1232 Add `ensure_no_std` build to CI
  .github/workflows/rust.yml
  Cargo.toml
  cairo_programs/benchmarks/field_arithmetic_get_square_benchmark.cairo
  ensure-no_std/Cargo.toml
  vm/Cargo.toml
  vm/src/math_utils/is_prime.rs
  vm/src/math_utils/mod.rs
Labels: pipelines

#1269 chore: ask about version in bug issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: pipelines

#1280 Run benchmarks serially in the CI
  .github/workflows/hyperfine.yml
Labels: pipelines

#1287 chore: move `take_until_unbalanced` to vm/serde
  .github/codecov.yml
  .github/workflows/publish.yml
  Cargo.lock
  Cargo.toml
  RELEASE.md
  deps/parse-hyperlinks/Cargo.lock
  deps/parse-hyperlinks/Cargo.toml
  deps/parse-hyperlinks/LICENSE
  deps/parse-hyperlinks/README.md
  deps/parse-hyperlinks/src/lib.rs
  vm/Cargo.toml
  vm/src/serde/deserialize_utils.rs
Labels: pipelines

#1240 Add fuzzer workflow
  .github/workflows/fuzzer.yml
Labels: coverage

#1292 "chore: use workspace package metadata"
  Cargo.toml
  RELEASE.md
  cairo-vm-cli/Cargo.toml
  felt/Cargo.toml
  hint_accountant/Cargo.toml
  vm/Cargo.toml
Labels: pipelines

#1227 Cairo fuzzer
  .github/workflows/fuzzer.yml
  fuzzer/Cargo.toml
  fuzzer/README.md
  fuzzer/json.dict
  fuzzer/src/fuzz_json.rs
Labels: pipelines, coverage
