Repository lambdaclass/cairo-vm, pull requests merged in 2023-08, with the labels that each got.

#1341 Fix: typos
  docs/python_vm/README.md
  docs/references_parsing/README.md
Labels: pipelines, coverage

#1344 Stabilize fuzz program & json
  fuzzer/Cargo.lock
  fuzzer/Cargo.toml
  fuzzer/json.dict
  fuzzer/src/fuzz_json.rs
  fuzzer/src/fuzz_program.rs
  vm/src/cairo_run.rs
  vm/src/serde/deserialize_program.rs
  vm/src/types/program.rs
Labels: pipelines, coverage

#1359 Pin nextest version in GH workflow
  .github/workflows/rust.yml
Labels: pipelines

#1360 Fix `VirtualMachineError::JumpRelNotInt` Display message
  vm/src/vm/errors/vm_errors.rs
Labels: coverage

#1356 Better json generation
  .github/workflows/fuzzer.yml
  fuzzer/Cargo.lock
  fuzzer/Cargo.toml
  fuzzer/src/fuzz_json.rs
  vm/src/cairo_run.rs
  vm/src/serde/deserialize_program.rs
Labels: pipelines, coverage

#1371 Fix branch matches in CI
  .github/workflows/hyperfine.yml
  .github/workflows/iai_pr.yml
  .github/workflows/rust.yml
  .github/workflows/test_install.yml
Labels: pipelines

#1373 cargo update for v0.8.6
  Cargo.lock
Labels: pipelines

#1377 update parse-hyperlinks version
  Cargo.lock
  Cargo.toml
  deps/parse-hyperlinks/Cargo.toml
Labels: pipelines

#1382 Remove duplicated code is dst deduction
  vm/src/vm/vm_core.rs
Labels: coverage

#1386 Add cli args description to readme
  README.md
Labels: coverage

#1388 Remove cairo1 & cairo2 folders in `clean` Makefile target
  Makefile
Labels: pipelines

#1390 Fix `cairo1` & `cairo2` builds in Makefile
  Makefile
Labels: pipelines

#1397 fix: Fix python build condition in `build_programs` job CI
  .github/workflows/rust.yml
Labels: high-priority, pipelines

#1419 Update hint accountant for tracking unimplemented hints
  .github/workflows/hint_accountant.yml
  hint_accountant/src/main.rs
  hint_accountant/whitelists/cairo_secp.json
  hint_accountant/whitelists/latest.json
  vm/src/lib.rs
Labels: pipelines

#1394 Compare air_public_inputs in CI
  .github/workflows/rust.yml
  Makefile
Labels: pipelines

#1409 Add rust toolchain + Update rust version used by CI
  .github/workflows/bench.yml
  .github/workflows/hint_accountant.yml
  .github/workflows/hyperfine.yml
  .github/workflows/iai_main.yml
  .github/workflows/iai_pr.yml
  .github/workflows/publish.yml
  .github/workflows/rust.yml
  rust-toolchain
Labels: pipelines

#1395 Use lambdawork's `UnsignedInteger.div_rem` instead of converting to `BigInt` in `Felt252.div_rem`
  felt/src/lib_lambdaworks.rs
Labels: coverage

#1391 Compare air_public_inputs against python vm + Fix how public memory is built
  .github/workflows/rust.yml
  .gitignore
  CHANGELOG.md
  Makefile
  vm/src/air_public_input.rs
  vm/src/tests/air_public_input_comparator.py
  vm/src/tests/compare_vm_state.sh
  vm/src/vm/errors/memory_errors.rs
  vm/src/vm/runners/cairo_runner.rs
  vm/src/vm/vm_core.rs
  vm/src/vm/vm_memory/memory_segments.rs
Labels: bug, enhancement, pipelines

#1422 Support Linux Mint as Ubuntu
  install.sh
Labels: pipelines

#1423 Use cairo-lang whitelists for the hint accountant + update cairo-lang version
  .github/workflows/hint_accountant.yml
  .gitignore
  Makefile
  hint_accountant/Cargo.toml
  hint_accountant/src/main.rs
  hint_accountant/whitelists/0.10.3.json
  hint_accountant/whitelists/0.6.0.json
  hint_accountant/whitelists/0.8.2.json
  hint_accountant/whitelists/384_bit_prime_field.json
  hint_accountant/whitelists/cairo_blake2s.json
  hint_accountant/whitelists/cairo_keccak.json
  hint_accountant/whitelists/cairo_secp.json
  hint_accountant/whitelists/cairo_sha256.json
  hint_accountant/whitelists/cairo_sha256_arbitrary_input_length.json
  hint_accountant/whitelists/ec_bigint.json
  hint_accountant/whitelists/ec_recover.json
  hint_accountant/whitelists/encode_packed.json
  hint_accountant/whitelists/latest.json
  hint_accountant/whitelists/uint256_improvements.json
  hint_accountant/whitelists/vrf.json
  requirements.txt
Labels: pipelines
