Repository lambdaclass/cairo-vm, pull requests merged in 2023-05, with the labels that each got.

#1028 perf: add benchmarks for runner initialization
  bench/criterion_benchmark.rs
  bench/iai_benchmark.rs
Labels: coverage

#1097 perf: use proof mode for Hyperfine benchmarks
  .github/workflows/hyperfine.yml
  Makefile
Labels: pipelines

#1118 Linear split test
  .gitignore
  cairo_programs/cairo-1-contracts/linear_split.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1124 Cairo program to test for `TestLessThan`/`TestLessThanOrEqual`
  cairo_programs/cairo-1-contracts/test_less_than.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1155 Add test for alloc constant size
  cairo_programs/cairo-1-contracts/alloc_constant_size.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1148 Add arena index hint test
  cairo_programs/cairo-1-contracts/get_segment_arena_index.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1140 Test for `Uint256DivMod` hint
  cairo_programs/cairo-1-contracts/uint256_div_mod.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1153 Test AssertLeIsFirstArcExcluded
  cairo_programs/cairo-1-contracts/dict_test.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1156 Add cairo program for testing AllocSegment hint
  cairo_programs/cairo-1-contracts/alloc_segment.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1104 Make a Cairo 1 program for testing SquareRoot & U256SquareRoot hint
  CHANGELOG.md
  cairo_programs/cairo-1-contracts/u128_sqrt.cairo
  cairo_programs/cairo-1-contracts/u16_sqrt.cairo
  cairo_programs/cairo-1-contracts/u256_sqrt.cairo
  cairo_programs/cairo-1-contracts/u32_sqrt.cairo
  cairo_programs/cairo-1-contracts/u64_sqrt.cairo
  cairo_programs/cairo-1-contracts/u8_sqrt.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1149 Make a Cairo 1 program for testing ShouldSkipSquashLoop hint
  cairo_programs/cairo-1-contracts/should_skip_squash_loop.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1152 ci: add contribution guide
  CONTRIBUTING.md
  README.md
Labels: pipelines

#1158 Implement widemul128 hint
  cairo_programs/cairo-1-contracts/widemul128.cairo
  src/hint_processor/cairo_1_hint_processor/hint_processor.rs
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1157 tests: Add test that runs a contract entrypoint using the hints `Felt252DictEntryUpdate`, `GetCurrentAccessIndex` & `GetCurrentAccessAccessDelta`
  cairo_programs/cairo-1-contracts/felt252_dict_entry_update.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1160 Add felt252 dict entry init hint test
  cairo_programs/cairo-1-contracts/felt252_dict_entry_init.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1094 test: add `proptest::Strategy` for generating arbitrary `Felt252`s
  Makefile
  felt/Cargo.toml
  felt/proptest-regressions/lib.txt
  felt/src/arbitrary.rs
  felt/src/lib.rs
Labels: tests, coverage

#1159 tests: Add test that runs a contract entrypoint using the hint `AssertLeFindSmallArcs` & `AssertLeIsSecondArcExcluded`
  cairo_programs/cairo-1-contracts/assert_le_find_small_arcs.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1142 Test RandomEcPoint hint & Fix for LinearSplit
  cairo_programs/cairo-1-contracts/random_ec_point.cairo
  src/hint_processor/cairo_1_hint_processor/hint_processor.rs
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1166 ci: run test_install action on PRs
  .github/workflows/test_install.yml
Labels: pipelines

#1163 Fix `U256SquareRoot` hint
  src/hint_processor/cairo_1_hint_processor/hint_processor.rs
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1162 Add test for hint FieldSqrt
  cairo_programs/cairo-1-contracts/field_sqrt.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1125 Alloc felt dict test
  cairo_programs/cairo-1-contracts/felt_252_dict.cairo
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1164 docs: add amendments for hotfix releases
  RELEASE.md
Labels: documentation, coverage

#1167 perf: migrate to iai-callgrind
  .github/workflows/iai_main.yml
  .github/workflows/iai_pr.yml
  Cargo.lock
  Cargo.toml
  Makefile
  bench/iai_benchmark.rs
Labels: pipelines

#1172 Update README.md
  README.md
Labels: coverage

#1174 Fix and tests for `Uint256DivMod`
  cairo_programs/cairo-1-contracts/uint256_div_mod.cairo
  src/hint_processor/cairo_1_hint_processor/hint_processor.rs
  src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: coverage

#1182 fix: typo in error message
  src/hint_processor/builtin_hint_processor/ec_utils.rs
Labels: coverage
