Repository lambdaclass/cairo-vm, pull requests merged in 2023-07, with the labels that each got.

#1288 chore: rename fibonacci and factorial benchmark files
  README.md
  cairo_programs/benchmarks/big_factorial.cairo
  cairo_programs/benchmarks/big_fibonacci.cairo
Labels: pipelines

#1300 Fix iai-benchmarks workflow
  .github/workflows/iai_main.yml
  .github/workflows/iai_pr.yml
Labels: pipelines

#1310 update fuzzer workflow
  .github/workflows/fuzzer.yml
Labels: pipelines

#1312 fix: check all features on each crate
  .github/workflows/rust.yml
  felt/src/lib_lambdaworks.rs
  vm/src/hint_processor/cairo_1_hint_processor/hint_processor.rs
  vm/src/hint_processor/cairo_1_hint_processor/hint_processor_utils.rs
Labels: pipelines

#1325 chore: add token to codecov action
  .github/workflows/rust.yml
Labels: pipelines

#1331 crash report issue workflow
  .github/ISSUE_TEMPLATE/crash_report.md
  .github/workflows/fuzzer.yml
Labels: pipelines

#1328 Add test for uint256_mul_div_mod possible overflow
  Makefile
  cairo_programs/uint256.cairo
  vm/src/tests/cairo_run_test.rs
Labels: coverage

#1333 fix: memory comparison script failing silently
  .github/workflows/rust.yml
  vm/src/tests/compare_vm_state.sh
Labels: pipelines

#1336 chore(fuzzer): bump `actions/checkout` from v2 to v3
  .github/workflows/fuzzer.yml
Labels: pipelines

#1329 refactor: change `bigint3_pack` uses for `BigInt3::pack86`
  fuzzer/Cargo.lock
  vm/src/hint_processor/builtin_hint_processor/ec_recover.rs
  vm/src/hint_processor/builtin_hint_processor/keccak_utils.rs
  vm/src/hint_processor/builtin_hint_processor/secp/bigint_utils.rs
  vm/src/hint_processor/builtin_hint_processor/secp/field_utils.rs
  vm/src/hint_processor/builtin_hint_processor/secp/secp_utils.rs
  vm/src/hint_processor/builtin_hint_processor/secp/signature.rs
  vm/src/hint_processor/builtin_hint_processor/uint_utils.rs
Labels: coverage

#1236 Fuzz cairo compiled programs
  Makefile
  fuzzer/Cargo.toml
  fuzzer/README.md
  fuzzer/cairo_programs/.gitkeep
  fuzzer/src/cairo_compiled_programs_fuzzer.rs
Labels: coverage

#1347 chore: add cairo 2 compilation to makefile
  Makefile
Labels: pipelines

#1351 fix: Program cmp depends on hints_ranges ordering
  CHANGELOG.md
  fuzzer/Cargo.lock
  fuzzer/src/cairo_compiled_programs_fuzzer.rs
  vm/src/serde/deserialize_program.rs
  vm/src/types/program.rs
  vm/src/utils.rs
  vm/src/vm/errors/vm_exception.rs
  vm/src/with_std.rs
  vm/src/without_std.rs
Labels: bug
