Repository lambdaclass/cairo-vm, pull requests merged in 2024-01, with the labels that each got.

#1520 ci: run tests with optimizations
  Cargo.toml
Labels: pipelines

#1521 ci: set default proptest limits
  .github/workflows/fresh_run.yml
  .github/workflows/rust.yml
  Cargo.toml
  Makefile
Labels: pipelines

#1519 ci: avoid collecting coverage data on local dev
  .github/workflows/rust.yml
  Makefile
Labels: pipelines

#1582 Add layout documentation in the cairo1-run crate
  cairo1-run/README.md
Labels: documentation, pipelines, cairo1run

#1586 Remove redundant memory_hole checks from cairo_run_tests module
  vm/src/tests/cairo_run_test.rs
  vm/src/tests/mod.rs
Labels: pipelines

#1588 Remove underscore prefix from test file names
  cairo_programs/keccak.cairo
  cairo_programs/keccak_alternative_hint.cairo
  cairo_programs/proof_programs/_keccak.cairo
  cairo_programs/proof_programs/_keccak_alternative_hint.cairo
  cairo_programs/proof_programs/keccak.cairo
  cairo_programs/proof_programs/keccak_alternative_hint.cairo
  vm/src/serde/serialize_program.rs
  vm/src/tests/cairo_run_test.rs
  vm/src/vm/runners/builtin_runner/keccak.rs
Labels: pipelines

#1581 Add `cairo_pie_output` flag to `cairo1-run`
  CHANGELOG.md
  cairo1-run/README.md
  cairo1-run/src/main.rs
Labels: cairo1run

#1575 Add `print_output` flag to `cairo-1` crate
  CHANGELOG.md
  cairo1-run/src/main.rs
  cairo_programs/cairo-1-programs/struct_span_return.cairo
Labels: cairo1run
