Repository lambdaclass/cairo-vm, pull requests merged in 2024-04, with the labels that each got.

#1656 Remove `#[allow(deprecated)]` & `#[allow(dead_code)]`
  vm/src/hint_processor/builtin_hint_processor/math_utils.rs
  vm/src/hint_processor/builtin_hint_processor/secp/secp_utils.rs
  vm/src/hint_processor/builtin_hint_processor/secp/signature.rs
  vm/src/hint_processor/cairo_1_hint_processor/dict_manager.rs
  vm/src/types/layout.rs
  vm/src/vm/vm_core.rs
Labels: pipelines

#1384 ci: optimize build checks
  .github/workflows/rust.yml
  bench/criterion_benchmark.rs
  bench/iai_benchmark.rs
  cairo-vm-cli/Cargo.toml
  cairo-vm-tracer/Cargo.toml
  cairo1-run/Cargo.toml
  vm/Cargo.toml
  vm/src/lib.rs
  vm/src/vm/vm_core.rs
Labels: pipelines

#1710 Fix cairo1-run `validate_layouts`
  cairo1-run/src/main.rs
Labels: pipelines

#1655 Remove `#[allow(clippy::format_collect)]`
  vm/src/vm/runners/cairo_pie.rs
Labels: pipelines

#1699 Add integration test using `range_check96`, `add_mod` & `mul_mod` builtins
  cairo_programs/mod_builtin_feature/apply_poly.cairo
  cairo_programs/mod_builtin_feature/proof/apply_poly.cairo
  vm/src/tests/cairo_run_test.rs
Labels: tests

#1711 Add Hyper Threading benchmarks workflow
  .github/workflows/hyper_threading_benchmarks.yml
  examples/hyper_threading/hyper-threading-workflow.sh
Labels: pipelines

#1725 Add bitwise program
  cairo1-run/src/main.rs
  cairo_programs/cairo-1-programs/bitwise.cairo
Labels: tests

#1719 Add option to pass Sierra programs to cairo1-run
  CHANGELOG.md
  Cargo.lock
  cairo1-run/Cargo.toml
  cairo1-run/README.md
  cairo1-run/src/main.rs
Labels: cairo1run

#1733 Remove python code from doc comments in `program_hash` module
  vm/src/program_hash.rs
Labels: documentation

#1740 Update broken links in READMEs
  README.md
  cairo1-run/README.md
Labels: documentation

#1741 [Cairo 1 Run] Refactor integration tests + check that return values taken from output segment are correct
  cairo1-run/src/cairo_run.rs
  cairo1-run/src/main.rs
Labels: tests
