Repository lambdaclass/cairo-vm, pull requests merged in 2024-02, with the labels that each got.

#1597 [Cairo1] Append return values to the output segment when running in proof_mode
  CHANGELOG.md
  cairo1-run/src/main.rs
  vm/src/vm/runners/builtin_runner/output.rs
  vm/src/vm/vm_core.rs
Labels: cairo1run

#1601 Refactor cairo1-run crate
  CHANGELOG.md
  cairo1-run/src/cairo_run.rs
  cairo1-run/src/main.rs
Labels: cairo1run

#1602 [Cairo1] Add a test to check that the output segment contains the return values when running in proof-mode
  cairo1-run/src/cairo_run.rs
Labels: tests, coverage, cairo1run

#1610 Remove leftover mentions of `lambdaworks-felt` feature
  README.md
  vm/src/lib.rs
Labels: documentation, coverage

#1615 Restore `flamegraph` target
  Makefile
Labels: pipelines

#1614 Use locked dependencies to install `cargo-nextest` & `wasm-pack`
  Makefile
Labels: bug, pipelines

#1605 Update Rust version to 1.74.1
  .github/workflows/bench.yml
  .github/workflows/cairo_1_programs.yml
  .github/workflows/fresh_run.yml
  .github/workflows/hint_accountant.yml
  .github/workflows/hyperfine.yml
  .github/workflows/iai_main.yml
  .github/workflows/iai_pr.yml
  .github/workflows/publish.yml
  .github/workflows/rust.yml
  Makefile
  README.md
  cairo1-run/src/cairo_run.rs
  rust-toolchain
  vm/src/hint_processor/builtin_hint_processor/find_element_hint.rs
  vm/src/hint_processor/cairo_1_hint_processor/hint_processor.rs
  vm/src/serde/deserialize_utils.rs
  vm/src/tests/mod.rs
  vm/src/vm/runners/builtin_runner/bitwise.rs
  vm/src/vm/runners/cairo_pie.rs
Labels: pipelines

#1639 Fix uint256_div_mod.cairo entrypoint
  vm/src/tests/cairo_1_run_from_entrypoint_tests.rs
Labels: tests
