Repository lambdaclass/cairo-vm, pull requests merged in 2025-04, with the labels that each got.

#2056 CI: Make cache keys depend on Cairo version
  .github/workflows/rust.yml
Labels: pipelines

#2062 fix: Add boundary tests for SecpSplitOutOfRange in secp_utils
  vm/src/hint_processor/builtin_hint_processor/secp/secp_utils.rs
Labels: tests

#2077 docs: add --run_from_cairo_pie documentation for Cairo 0 and Cairo 1
  README.md
Labels: documentation
