Repository lambdaclass/cairo-vm, pull requests merged in 2025-03, with the labels that each got.

#1990 Update_to_rustc_1.85
  .github/workflows/bench.yml
  .github/workflows/cairo_1_programs.yml
  .github/workflows/fresh_run.yml
  .github/workflows/hint_accountant.yml
  .github/workflows/hyper_threading_benchmarks.yml
  .github/workflows/hyperfine.yml
  .github/workflows/iai_main.yml
  .github/workflows/iai_pr.yml
  .github/workflows/publish.yml
  .github/workflows/rust.yml
  CHANGELOG.md
  README.md
  rust-toolchain
  vm/src/air_public_input.rs
  vm/src/cairo_run.rs
  vm/src/hint_processor/builtin_hint_processor/signature.rs
  vm/src/hint_processor/builtin_hint_processor/uint256_utils.rs
  vm/src/hint_processor/builtin_hint_processor/vrf/fq.rs
  vm/src/hint_processor/cairo_1_hint_processor/dict_manager.rs
  vm/src/hint_processor/cairo_1_hint_processor/hint_processor.rs
  vm/src/math_utils/mod.rs
  vm/src/program_hash.rs
  vm/src/serde/deserialize_program.rs
  vm/src/serde/deserialize_utils.rs
  vm/src/vm/decoding/decoder.rs
  vm/src/vm/runners/builtin_runner/modulo.rs
  vm/src/vm/runners/cairo_pie.rs
  vm/src/vm/vm_core.rs
  vm/src/vm/vm_memory/memory.rs
Labels: pipelines

#1991 Update CI
  .github/workflows/bench.yml
  .github/workflows/cairo_1_programs.yml
  .github/workflows/fresh_run.yml
  .github/workflows/fuzzer.yml
  .github/workflows/hint_accountant.yml
  .github/workflows/hyper_threading_benchmarks.yml
  .github/workflows/hyperfine.yml
  .github/workflows/iai_main.yml
  .github/workflows/iai_pr.yml
  .github/workflows/publish.yml
  .github/workflows/rust.yml
  .github/workflows/test_install.yml
  Makefile
Labels: pipelines

#1997 Fix another issue with external contributors in ci
  .github/workflows/hyper_threading_benchmarks.yml
Labels: pipelines

#2006 Improve documentation
  vm/src/cairo_run.rs
  vm/src/vm/vm_memory/memory.rs
Labels: documentation

#2005 Fix comment in `initialize_builtins()`
  vm/src/vm/runners/cairo_runner.rs
Labels: documentation

#2018 Removed CODEOWNERS file
  CODEOWNERS
Labels: pipelines

#2025 CI: run main workflows also on starkware-development branch
  .github/workflows/bench.yml
  .github/workflows/cairo_1_programs.yml
  .github/workflows/hint_accountant.yml
  .github/workflows/hyper_threading_benchmarks.yml
  .github/workflows/iai_main.yml
  .github/workflows/rust.yml
  .github/workflows/test_install.yml
Labels: pipelines

#2026 CI: Fix cache not found error
  .github/workflows/rust.yml
Labels: pipelines

#2019 Add Commit Signing section
  CONTRIBUTING.md
Labels: pipelines

#2037 Update changelog.yml
  .github/workflows/changelog.yml
Labels: pipelines, nochangelog
